# Generated by Django 5.2.4 on 2025-09-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathewellapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='confirmpassword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
