# Generated by Django 5.1.7 on 2025-09-18 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathewellapp', '0003_environmentaldata_wearabledata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm25', models.FloatField()),
                ('co', models.FloatField()),
                ('heart_rate', models.IntegerField()),
                ('spo2', models.IntegerField()),
                ('risk_level', models.CharField(max_length=10)),
                ('advisory', models.TextField()),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
