# Generated by Django 5.1.7 on 2025-09-21 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breathewellapp', '0005_historicaldata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalData',
        ),
    ]
