# Generated by Django 5.1.7 on 2025-09-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathewellapp', '0007_historicaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='alertthreshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='medicalconditions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='notificationmethod',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
