# Generated by Django 5.1.7 on 2025-12-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathewellapp', '0008_register_alertthreshold_register_allergies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.FloatField()),
                ('value2', models.FloatField()),
                ('value3', models.FloatField()),
                ('value6', models.CharField(blank=True, max_length=100)),
                ('value7', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'sensordata',
                'managed': False,
            },
        ),
    ]
