# Generated by Django 5.1.7 on 2025-12-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathewellapp', '0009_sensordata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskprediction',
            name='recorded_at',
        ),
        migrations.AddField(
            model_name='riskprediction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
