# Generated by Django 5.1.7 on 2025-12-17 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breathewellapp', '0010_remove_riskprediction_recorded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskprediction',
            name='created_at',
        ),
    ]
