# Generated by Django 5.1.7 on 2025-12-17 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathewellapp', '0011_remove_riskprediction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprediction',
            name='reading_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 17, 6, 16, 45, 769494)),
        ),
    ]
