# Generated by Django 5.1.7 on 2025-12-17 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathewellapp', '0012_riskprediction_reading_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskprediction',
            name='reading_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 17, 6, 22, 6, 172648)),
        ),
    ]
