# Generated by Django 5.1.3 on 2026-01-19 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathewellapp', '0013_alter_riskprediction_reading_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollutedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.IntegerField(default=100)),
            ],
        ),
        migrations.AlterField(
            model_name='riskprediction',
            name='reading_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 20, 0, 51, 20, 755267)),
        ),
    ]
